---
# Setup MySQL Repository

- name: Adding MariaDB Repository Key
  apt_key: keyserver=keyserver.ubuntu.com id=0xF1656F24C74CD1D8
  register: apt_key

- name: Adding MariaDB Repository
  apt_repository: repo='deb [arch=amd64,i386,ppc64el] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.1/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main' state=present filename=mariadb
  register: repository

- include: roles/libs/tasks/apt/update.yml
  when: repository.changed == True or apt_key.changed == True
