---
# Print Userful Information

- name: AnsiPress HTTP Auth Details
  debug:
    msg: "{{ item }}"
  with_items:
    - HTTP AUTH Username = AnsiPress
    - HTTP AUTH Password = {{ http_auth_pass }}
  when: setup_http_auth.stat.islnk is not defined

- name: Getting WordPress Setup Information
  debug:
    msg: "{{ item }}"
  with_items:
    - WordPress Username = {{ username | lower }}
    - WordPress Password = {{ random_password.stdout }}
  when: website_type == "wp" or website_type == "w3tc" or website_type == "wpfc"
