---
- include: roles/website/tasks/html.yml

# Setup PHP Website Pool
- name: Setup {{ username | lower }} Pool, Hold on...
  template: src=php/pool.conf dest=/etc/php/7.1/fpm/pool.d/{{ username | lower }}.conf

#- name: Setup php7.1-{ username | lower }} Service, Hold on...
- template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "php/php7.1-fpm", dest: "/etc/init.d/php7.1-{{ username | lower }}" }
    - { src: "php/php7.1-fpm.service", dest: "/lib/systemd/system/php7.1-{{ username | lower }}.service" }
  notify: service php7.1-{{ username | lower }} restart
